language: common-lisp
sudo: required

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -s prove -e '(progn (ql:quickload (list :cl-handlers :cl-handlers-test) (or (prove:run :cl-handlers-test) (uiop:quit -1)))'